### ISSUE TITLE
Can't get default fonts on Ubuntu

### ISSUE THREAD

**Issue by a-a-k** [VahidN/PdfReport.Core#40]
# Summary of the issue

Can't build a report.

## Environment

```
PdfReport.Core version: latest
.NET Core SDK version: 3
OS:  Ubuntu 18.04
```

## Example code/Steps to reproduce:

        [HttpGet]
        [Route("api/pdf")]
        public IActionResult GetPdf()
        {
            var stream = new MemoryStream();
            new PdfReport()
                .MainTableDataSource(source => source.StronglyTypedList(new []{"blah, blah"}))
                .MainTableEvents(events =>
                    events.MainTableCreated(arg =>
                    {
                        var infoTable = new PdfGrid(numColumns: 1)
                        {
                            WidthPercentage = 100
                        };

                        infoTable.AddSimpleRow(
                            (cellData, properties) =>
                            {
                                cellData.Value = "hello world";
                                properties.PdfFont = events.PdfFont;
                                properties.RunDirection = PdfRunDirection.LeftToRight;
                            });

                        var table = infoTable.AddBorderToTable(borderColor: BaseColor.LightGray, spacingBefore: 10f);
                        table.SpacingAfter = 10f;
                        arg.PdfDoc.Add(table);
                    }))
                .Generate(file => file.AsPdfStream(stream, false));

            stream.Position = 0;

            return File(stream, "application/pdf", "Output.pdf");
        }

## Output:

```
Exception message: System.IO.DirectoryNotFoundException:  directory does not exist.
Full Stack trace: 
System.IO.DirectoryNotFoundException:  directory does not exist.
   at PdfRpt.Core.Helper.Guard.CheckDirectoryExists(String fileName)
   at PdfRpt.GenericFontProvider..ctor(String mainFontPath, String defaultFontPath)
   at PdfRpt.FluentInterface.DataTemplate.setDefaultPdfFonts()
   at PdfRpt.FluentInterface.DataTemplate.get_PdfFont()
   at PdfRpt.FluentInterface.MainTableEventsBuilder..ctor(PdfReport pdfReport)
   at PdfRpt.FluentInterface.PdfReport.MainTableEvents(Action`1 mainTableEventsBuilder)
   at ReportingServer.PdfApiController.GetPdf() in PdfApiController.cs:line 18
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

```

**Comment by VahidN** [comment]
You should register the default fonts as the posted samples, [like this one](https://github.com/VahidN/PdfReport.Core/blob/master/PdfRpt.Core.SampleWebApp/Reports/InMemoryPdfReport.cs#L36).
