### ISSUE TITLE
Can't build a report in Ubuntu.

### ISSUE THREAD

**Issue by MedinaVla** [VahidN/PdfReport.Core#59]
# Summary of the issue

## Environment
PdfReport.Core 1.4.5
.NET Core SDK version: 6
OS:  Ubuntu 22.04
```
PdfReport.Core version:
.NET Core SDK version: 
IDE: 
```

## Example code/Steps to reproduce:

```
 public PdfReport GetPdfContentAsync(IEnumerable<AssetResponse> mapped, string title)
        {
            try
            {
                var dateFormat = GetDateFormat();

                return new PdfReport().DocumentPreferences(doc =>
                    {
                        doc.RunDirection(PdfRunDirection.LeftToRight);//In this line i get the error
                        doc.Orientation(PageOrientation.Landscape);
                        doc.PageSize(PdfPageSize.A4);
                        doc.PrintingPreferences(new PrintingPreferences
                        {
                            PickTrayByPdfSize = true
                        });
```

## Output:

```
System.IO.DirectoryNotFoundException:  directory does not exist.
   at PdfRpt.Core.Helper.Guard.CheckDirectoryExists(String fileName)
   at PdfRpt.GenericFontProvider..ctor(String mainFontPath, String defaultFontPath)
   at PdfRpt.FluentInterface.DataTemplate.setDefaultPdfFonts()
   at PdfRpt.FluentInterface.DataTemplate.get_PdfFont()
   at PdfRpt.FluentInterface.PagesFooterBuilder..ctor(PdfReport pdfReport)
   at PdfRpt.FluentInterface.PdfReport.PagesFooter(Action`1 pagesFooterBuilder)

```

**Comment by VahidN** [comment]
[Set this path correctly](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/IListPdfReport.cs#L169).
