### ISSUE TITLE
PDF Report Export Not Working

### ISSUE THREAD

**Issue by AndyEV** [VahidN/PdfReport.Core#7]
So I tried using the library for my dotnet core 1.1 application. As instructed I followed the step and pulled data from my database and passed it to the extension class that has the PdfReport code well define.

So every time I try exporting my data I keep getting NullReferenceExeption when it get to this line:
`
return document.GenerateAsByteArray();
`
Don't really understand why that is happening, I've cross check several time Debug and compare with what's done on the repository still, when it get the return line it throws NullReference Exception.

Please what do you think I really missed? Lemme know if you need to see the code thanks.

**Comment by VahidN** [comment]
You should follow the stack trace to see where is the origin of the exception.

**Comment by VahidN** [comment]
Try V1.1.1. It will show you the complete stack trace.

**Comment by AndyEV** [comment]
Sorry for the late reply, I did install V1.1.1 and am not clear with the stack trace below

`
System.NullReferenceException: Object reference not set to an instance of an object.
   at PdfRpt.Core.PdfTable.RowsManager.addExtraHeaderRows(String name)
   at PdfRpt.Core.PdfTable.RowsManager.TableInitAddHeaderAndFooter()
   at PdfRpt.Core.PdfTable.RowsManager.applyRowSettings(IList`1 row)
   at PdfRpt.Core.PdfTable.RowsManager.addSingleRow(IList`1 row)
   at PdfRpt.Core.PdfTable.RowsManager.printNormalTable()
   at PdfRpt.Core.PdfTable.RowsManager.AddMainTableRows()
   at PdfRpt.Core.PdfTable.RenderMainTable.AddToDocument()
   at PdfRpt.PdfReportDocument.createPdf()
   at PdfRpt.PdfReportDocument.GeneratePdf()
   at exam.admin.Extensions.TestResultPDFExportExtension.CreateInMemoryPdfReport(String wwwroot, String testname, String course, Decimal passScore, Decimal totalScore, List`1 pushdata) in C:\Development\Projects\Private\examportal-v1\src\exam.admin\Extensions\TestResultPDFExportExtension.cs:line 115
   at exam.admin.Controllers.TechController.export_pdf(Nullable`1 id) in C:\Development\Projects\Private\examportal-v1\src\exam.admin\Controllers\TechController.cs:line 295
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
`

**Comment by AndyEV** [comment]
Thanks... I actually saw what the issues was, I added 
`column.AddHeadingCell(string.Empty); `
to the first column that has serials that was the reason I kept having the NullReference. After removing it, it work perfectly well
