### ISSUE TITLE
Page break before and after report

### ISSUE THREAD

**Issue by SirwanAfifi** [VahidN/PdfReport.Core#8]
I should have asked [this question](https://github.com/VahidN/PdfReport/issues/3#issue-262361593) here because I am using the Core version. Now I can pass image to the template based on your suggestion 👍 it works like a charm, Now the problem is that it adds a page before and another page after the main report, I went through the template but I couldn't find a clue to solve it! (also tried to use several templates). Here's the code for generating the report, it would be great if you could help me out:
```
public static class TestReport
{
    public static byte[] CreateInMemoryPdfReport(string wwwroot, OrderDto order)
    {
        return new PdfRpt.FluentInterface.PdfReport().DocumentPreferences(doc =>
            {
                doc.RunDirection(PdfRunDirection.RightToLeft);
                doc.Orientation(PageOrientation.Portrait);
                doc.PageSize(PdfPageSize.A4);
                doc.DocumentMetadata(new DocumentMetadata
                {
                    Author = "Company Name",
                    Subject = "Subject",
                    Title = "Title"
                });
                doc.Compression(new CompressionSettings
                {
                    EnableCompression = true,
                    EnableFullCompression = true
                });
            })
            .DefaultFonts(fonts =>
            {
                fonts.Path(Path.Combine(wwwroot, "fonts", "Samim-Bold.ttf"),
                    Path.Combine(wwwroot, "fonts", "Samim-Bold.ttf"));
                fonts.Size(9);
                fonts.Color(System.Drawing.Color.Black);
            })
            .PagesFooter(footer =>
            {
                //footer.DefaultFooter(printDate: DateTime.Now.ToString("MM/dd/yyyy"));
            })
            .MainTableTemplate(template =>
            {
                template.BasicTemplate(BasicTemplate.NullTemplate);
            })
            .MainTablePreferences(table =>
            {
                table.ColumnsWidthsType(TableColumnWidthType.Relative);
            })
            .MainTableDataSource(dataSource =>
            {
                var listOfRows = new List<OrderDto>();
                listOfRows.Add(order);
                dataSource.StronglyTypedList(listOfRows);
            })
            .MainTableColumns(columns =>
            {
                columns.AddColumn(column =>
                {
                    column.PropertyName<OrderDto>(x => x.Id);
                    column.HeaderCell(caption: "Title");
                    column.Width(6);
                    column.CellsHorizontalAlignment(HorizontalAlignment.Center);
                    column.IsVisible(true);
                    column.Order(1);
                    column.ColumnItemsTemplate(template =>
                    {
                        template.PdfTemplate(
                            pdfTemplatePath: System.IO.Path.Combine(wwwroot, "reports/Template.pdf"),
                            onFillAcroForm: (data, form, pdfStamper) =>
                            {
                                form.GenerateAppearances = true;
                                
                                form.SetField("txtDate", order.DateTime);
                                form.SetField("txtDeliveyDate", order.DeliveryDate);
                                form.SetField("txtCustomerCode", order.CustomerId);
                                form.SetField("txtCustomerFullName", order.CustomerFullName);
                                form.SetField("txtOrderCode", order.Code);
                                // other fields
                                
                                PushbuttonField ad = form.GetNewPushbuttonFromField("myImage");
                                ad.Layout = PushbuttonField.LAYOUT_ICON_ONLY;
                                ad.ProportionalIcon = true;
                                // test image
                                var file = wwwroot + "/uploads/2cda5dbd-5153-43e9-bbf1-d707eb23e6a8.jpg";
                                byte[] bytes = System.IO.File.ReadAllBytes(file);
                                ad.Image = new Jpeg(bytes);
                                form.ReplacePushbuttonField("myImage", ad.Field);
                            });
                    });
                });
            })
            .Export(export => { export.ToExcel(); }).GenerateAsByteArray();
        ;
    }
}
```
### PS:
**1)**: This is a single entity to be shown to the user, so as you see I had to pass a list to the `MainTableDataSource` (I guess it might be because of this ):
```
.MainTableDataSource(dataSource =>
{
    var listOfRows = new List<OrderDto>();
    listOfRows.Add(order);
    dataSource.StronglyTypedList(listOfRows);
})
```
**2)**: One more thing, when I uncomment this line of code:
`footer.DefaultFooter(printDate: DateTime.Now.ToString("MM/dd/yyyy"));`
I get following exception:
```
Exception: Object reference not set to an instance of an object  at MyProject.PdfReport.TestReport.<>c__DisplayClass0_0.<CreateInMemoryPdfReport>b__9(IList`1 data, AcroFields form, PdfStamper pdfStamper) in C:\Users\Sirwa\Documents\Projects\ASP.NET\myProject\src\MyProject.PdfReport\TestReport.cs:line 92
   at PdfRpt.Core.Helper.PdfImageHelper.GetITextSharpImageFromAcroForm(PdfWriter pdfWriter, String pdfTemplateFilePath, IList`1 data, Action`3 onFillAcroForm, IList`1 fonts, Int32 pageNumber)
   at PdfRpt.ColumnsItemsTemplates.PdfTemplateField.createImageFromImportedPage(CellAttributes attributes)
   at PdfRpt.ColumnsItemsTemplates.PdfTemplateField.RenderingCell(CellAttributes attributes)
   at PdfRpt.Core.Helper.TableCellDefinitionsExt.CreateSafePdfPCell(CellAttributes pdfRptTableCellDefinition, IColumnItemsTemplate defaultItemTemplate)
   at PdfRpt.Core.PdfTable.TableCellHelper.AddGeneralCell(BaseColor backgroundColor, BaseColor foreColor, Object rawData, Int32 columnNumber, RowType pdfRowType, CellType pdfCellType, IList`1 rowValues, HorizontalAlignment horizontalAlignment, DocumentFontStyle pdfFontStyle, Int32 rotation, Boolean setItemTemplate, Int32 colSpan)
   at PdfRpt.Core.PdfTable.TableCellHelper.AddRowCell(IList`1 rowValues, BaseColor backgroundColor, BaseColor foreColor, Int32 columnNumber)
   at PdfRpt.Core.PdfTable.RowsManager.addTableRow(IList`1 rowData, BaseColor backgroundColor, BaseColor foreColor)
   at PdfRpt.Core.PdfTable.RowsManager.addSingleRow(IList`1 row)
   at PdfRpt.Core.PdfTable.RowsManager.printNormalTable()
   at PdfRpt.Core.PdfTable.RowsManager.AddMainTableRows()
   at PdfRpt.Core.PdfTable.RenderMainTable.AddToDocument()
   at PdfRpt.PdfReportDocument.createPdf()
   at PdfRpt.PdfReportDocument.GeneratePdf()
   at MyProject.PdfReport.TestReport.CreateInMemoryPdfReport(String wwwroot, OrderDto order) in C:\Users\Sirwa\Documents\Projects\ASP.NET\myProject\src\MyProject.PdfReport\TestReport.cs:line 24
   at MyProject.Controllers.HomeController.Index() in C:\Users\Sirwa\Documents\Projects\ASP.NET\myProject\src\MyProject\Controllers\HomeController.cs:line 28
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
```

**Comment by VahidN** [comment]
- Is you template too large or has a long height larger than the page's height?
- A suggestion: If there is only one record and also it's table like, just use the pure iTextSharp. You can create that table with PdfPTable very easily, without using any templates. Or try HtmlWorker.

**Comment by SirwanAfifi** [comment]
This was the problem: 👍 

> Is your template too large or has a long height larger than the page's height? Try to reduce the size of your template.

now it's working. many thanks.

one more thing:
I also followed your suggestion, But it seems that `HtmlWorker` doesn't support string interpolation
```
private string createHtmlSnippet(OrderReportViewModel order)
{
    return $@"<b>{order.Title}</b>
             <br/>
             <span style='color:blue;font-size:20pt;font-family:tahoma;font-style:italic;font-weight:bold'>
                <b>{order.Description}<b/>
            </span>";
}
```
